galeria/urls.py
from django.urls import path
from galeria.views import index, imagem, buscar

urlpatterns = [
    path('', index, name='index'),
    path('imagem/<int:foto_id>', imagem, name='imagem'),
    path('buscar', buscar, name='buscar')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('galeria.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

galeria/models.py
from django.db import models
from datetime import datetime

OPCOES_CATEGORIA = {
    ("NEBULOSA", "Nebulosa"),
    ("ESTRELA", "Estrela"),
    ("GALÁXIA", "Galáxia"),
    ("PLANETA", "Planeta")
}

class Fotografia(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    legenda = models.CharField(max_length=150, null=False, blank=False)
    categoria = models.CharField(max_length=100, choices=OPCOES_CATEGORIA, default='')
    descricao = models.TextField(null=False, blank=False)
    #foto = models.CharField(max_length=100, null=False, blank=False)
    foto = models.ImageField(upload_to="fotos/%Y/%m/%d/", blank=True)
    publicada = models.BooleanField(default=False)
    data_fotografia = models.DateTimeField(default=datetime.now, blank=False)

    def __str__(self):
        #return f"Fotografia [nome={self.nome}]"
        return self.nome

galeria/views.py
from django.shortcuts import render, get_object_or_404
from galeria.models import Fotografia

def index(request):
    #fotografias = Fotografia.objects.all()
    fotografias = Fotografia.objects.order_by("data_fotografia").filter(publicada=True)
        
    return render(request, 'galeria/index.html', {"cards": fotografias})

def imagem(request, foto_id):
    fotografia = get_object_or_404(Fotografia, pk=foto_id)
    return render(request, 'galeria/imagem.html', { "fotografia":fotografia })

def buscar(request):
    fotografias = Fotografia.objects.order_by("data_fotografia").filter(publicada=True)

    if "buscar" in request.GET:
        nome_a_buscar = request.GET["buscar"]

        if nome_a_buscar:
            fotografias = fotografias.filter(nome__icontains=nome_a_buscar)

    return render(request, "galeria/buscar.html", {"cards": fotografias})

templates/galeria/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alura Space</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/styles/style.css' %}">
</head>
<body>
    <div class="pagina-inicial">   
        {% include 'galeria/partials/_cabecalho.html' %}    
            <main class="principal">  
                {% include 'galeria/partials/_menu-lateral.html' %}   
                {% block content %}{% endblock %}   
            </main>    
    </div>      
    {% include 'galeria/partials/_footer.html' %}
</body>
</html>

templates/galeria/buscar.html
{% extends 'galeria/base.html' %}
{% load static %}
{% block content %}

            <section class="conteudo">
                <section class="banner">
                    <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
                    <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
                </section>
                <section class="tags">
                    <p class="tags__titulo">Busque por tags:</p>
                    <ul class="tags__lista">
                        <li class="tags__tag">Nebulosa</li>
                        <li class="tags__tag">Estrela</li>
                        <li class="tags__tag">Galáxia</li>
                        <li class="tags__tag">Planeta</li>
                    </ul>
                </section>
                <section class="galeria">
                    <div class="cards">
                        <h2 class="cards__titulo">Navegue pela galeria</h2>
                        <ul class="cards__lista">
                            {% if cards %}
                            {% for fotografia in cards %}                            
                            <li class="card">
                                <a href="{% url 'imagem' fotografia.id %}">
                                {% if fotografia.foto == "" or fotografia.foto == null %}
                                    <img class="card__imagem" src="{% static '/assets/imagens/galeria/image-not-found.png' %}" alt="foto">
                                {% else %}
                                    <img class="card__imagem" src="{{ fotografia.foto.url }}" alt="foto">
                                {% endif %}
                                </a>
                                <span class="card__tag">{{ fotografia.get_categoria_display }}</span>
                                <div class="card__info">
                                    <p class="card__titulo">{{ fotografia.nome }}</p>
                                    <div class="card__texto">
                                        <p class="card__descricao">{{ fotografia.legenda }}</p>
                                        <span>
                                            <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                                        </span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}          
                            {% else %}       
                            <div class="imagem__texto">
                                <p>Nenhuma fotografia encontrada!</p>
                            </div>
                            {% endif %}           
                        </ul>
                    </div>
                </section>
            </section>

{% endblock %}

templates/galeria/imagem.html
{% extends 'galeria/base.html' %}
{% load static %}
{% block content %}

            <section class="conteudo">
                <section class="imagem">
                    <div class="imagem__conteudo">
                        {% if fotografia.foto == "" or fotografia.foto == null %}
                        <img class="card__imagem" src="{% static '/assets/imagens/galeria/image-not-found.png' %}" alt="foto">
                        {% else %}
                        <img class="imagem__imagem" src="{{ fotografia.foto.url }}">
                        {% endif %}
                        <div class="imagem__info">
                            <div class="imagem__texto">
                                <p class="imagem__titulo">{{ fotografia.nome }}</p>
                                <p class="imagem__descricao">{{ fotografia.legenda }}</p>
                                <p class="imagem__texto">{{ fotografia.descricao }}</p>
                            </div>
                        </div>
                    </div>
                </section>
            </section>
{% endblock %}

templates/galeria/index.html
{% extends 'galeria/base.html' %}
{% load static %}
{% block content %}

            <section class="conteudo">
                <section class="banner">
                    <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
                    <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
                </section>
                <section class="tags">
                    <p class="tags__titulo">Busque por tags:</p>
                    <ul class="tags__lista">
                        <li class="tags__tag">Nebulosa</li>
                        <li class="tags__tag">Estrela</li>
                        <li class="tags__tag">Galáxia</li>
                        <li class="tags__tag">Planeta</li>
                    </ul>
                </section>
                <section class="galeria">
                    <div class="cards">
                        <h2 class="cards__titulo">Navegue pela galeria</h2>
                        <ul class="cards__lista">
                            {% if cards %}
                            {% for fotografia in cards %}                            
                            <li class="card">
                                <a href="{% url 'imagem' fotografia.id %}">
                                {% if fotografia.foto == "" or fotografia.foto == null %}
                                    <img class="card__imagem" src="{% static '/assets/imagens/galeria/image-not-found.png' %}" alt="foto">
                                {% else %}
                                    <img class="card__imagem" src="{{ fotografia.foto.url }}" alt="foto">
                                {% endif %}
                                </a>
                                <span class="card__tag">Estrelas</span>
                                <div class="card__info">
                                    <p class="card__titulo">{{ fotografia.nome }}</p>
                                    <div class="card__texto">
                                        <p class="card__descricao">{{ fotografia.legenda }}</p>
                                        <span>
                                            <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                                        </span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}          
                            {% else %}       
                            {% endif %}           
                        </ul>
                    </div>
                </section>
            </section>

{% endblock %}

templates/galeria/partials/_cabecalho.html
{% load static %}
<header class="cabecalho">
    <img src="{% static '/assets/logo/Logo(2).png' %}" alt="Logo da Alura Space" />
    <div class="cabecalho__busca">
        <div class="busca__fundo">
            <form action="{% url 'buscar' %}">

                <input class="busca__input" type="text" name="buscar" placeholder="O que você procura?">
                <button type="submit">
                    <img class="busca__icone" src="{% static '/assets/ícones/1x/search.png' %}" alt="ícone de search">
                </button>
            </form>
        </div>
    </div>
</header>

templates/galeria/partials/_footer.html
{% load static %}
<footer class="rodape">
    <div class="rodape__icones">
        <a href="https://twitter.com/AluraOnline" target=”_blank” >
            <img src="{% static '/assets/ícones/1x/twitter.png' %}" alt="ícone twitter">
        </a>
        <a href="https://www.instagram.com/aluraonline/" target=”_blank” >
            <img src="{% static '/assets/ícones/1x/instagram.png' %}" alt="ícone instagram">
        </a>
    </div>
    <p class="rodape__texto">Desenvolvido por Alura</p>
</footer>

templates/galeria/partials/_menu-lateral.html
{% load static %}
<section class="menu-lateral">
    <nav class="menu-lateral__navegacao">
        <a href="{% url 'index' %}"><img src="{% static '/assets/ícones/1x/Home - ativo.png' %}"> Home</a>
        <a href="#"><img src="{% static '/assets/ícones/1x/Mais vistas - inativo.png' %}"> Mais vistas</a>
        <a href="#"><img src="{% static '/assets/ícones/1x/Novas - inativo.png' %}"> Novas</a>
        <a href="#"><img src="{% static '/assets/ícones/1x/Surpreenda-me - inativo.png' %}"> Surpreenda-me</a>
    </nav>
</section>